import type { Metadata } from "next";
import { Inter } from "next/font/google";

import "./globals.css";

import ReactQueryProvider from "@/providers/react-query-provider";
import CustomThemeProvider from "@/providers/theme-provider";

import ToasterContainer from "@/components/ToasterContainer/ToasterContainer";

// const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" dir="rtl">
      <body
        className={"min-h-screen bg-[url('/assets/background.svg')] bg-fixed"}
      >
        <ReactQueryProvider>
          <CustomThemeProvider>
            <ToasterContainer />
            {children}
          </CustomThemeProvider>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
