import ReactQueryProvider from "@/providers/react-query-provider";
import CustomThemeProvider from "@/providers/theme-provider";
import { SessionProvider } from "next-auth/react";

import "./globals.css";

import { theme } from "@/themes/theme";

import ToasterContainer from "@/components/ToasterContainer/ToasterContainer";

// const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
  session,
}: Readonly<{
  children: React.ReactNode;
  session?: any;
}>) {
  return (
    <html lang="en" dir="rtl">
      <body
        className={"min-h-screen bg-[url('/assets/background.svg')] bg-fixed"}
      >
        <SessionProvider session={session}>
          <ReactQueryProvider>
            <CustomThemeProvider theme={theme}>
              <ToasterContainer />
              {children}
            </CustomThemeProvider>
          </ReactQueryProvider>
        </SessionProvider>
      </body>
    </html>
  );
}
